site_name: tm-admin
site_description: Classes for administrative functions for Tasking Manager style projects.
# strict: true
site_url: "https://www.hotosm.org"

repo_name: "hotosm/tm-admin"
repo_url: "https://github.com/hotosm/tm-admin/"
edit_uri: "edit/main/docs/"

extra:
  social:
    - icon: "fontawesome/brands/github"
      link: "https://github.com/hotosm/"
    - icon: "fontawesome/brands/twitter"
      link: "https://twitter.com/hotosm"
    - icon: "fontawesome/solid/globe"
      link: "https://www.hotosm.org"
  copyright: Copyright &copy; 2010 HOTOSM
  generator: false

theme:
  name: material
  palette:
    primary: custom
  favicon: images/favicon.png
  logo: images/hot_logo.png
  # custom_dir: docs/overrides

extra_css:
  - css/extra.css

markdown_extensions:
  - tables
  - toc:
      permalink: true
      title: Page contents
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.extra
  - pymdownx.emoji:
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  #  - mkdocs_protobuf:
  #      proto_dir: */*.proto *.proto
  - search
  - git-revision-date-localized
  - exclude:
      glob:
        - plugins/*
        - __pycache__/*
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          options:
            members_order: source
            separate_signature: true
            filters: ["!^_"]
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true

nav:
  - Home: index.md
  - About: about.md
  - Utilities:
      - tmadmin-manager: tmadmin-manage.md
      - tmdb: tmdb.md
      - generator: generator.md
  - Getting Started: getting_started.md
  - Importing TM data: importing.md
  - Deep Dives:
      - Building: build.md
      - Configuring: configuring.md
      - Communication: communication.md
      - Data Flow: dataflow.md
      - Data Exchange: dataexchange.md
      - Endpoints: endpoints.md
      - Database schema: schema.md
  - For Developers:
      - Code Structure: structure.md
      - Database Support: pgsupport.md
      - Code API:
          - Top Level APIs: api.md
          - Projects Table: api/projects.md
          - Tasks Table: api/tasks.md
          - Users Table: api/users.md
          - Campaigns Table: api/campaigns.md
          - Messages Table: api/messages.md
          - Organizations Table: api/organizations.md
      - Using asyncpg: pgasync.md
      - Protobuf API: protos-api.md
      - Class Hierarchy: apidocs/html/index.html
      - Versioning: https://docs.hotosm.org/dev-guide/version-control/#creating-releases
  - License: LICENSE.md
  - Changelog: CHANGELOG.md
  - Code of Conduct: https://docs.hotosm.org/code-of-conduct
