---
# This file is used to generate the full SQL to create database
# tables, as well as the protobuf files.

- task_history:
#    - id:
#        - int64
#        - required: true
#    - project_id:
#        - int64
#        - required: true
#    - task_id:
#        - int64
#        - required: true
    - action:
        - string
        - required: true
    - action_text:
        - string
    - action_date:
        - timestamp
        - required: true
    - user_id:
        - int64
        - required: true
