---
# This file is used to generate the full SQL to create database
# tables, as well as the protobuf files.

- task_history:
    - action:
        - public.taskaction
        - required: true
    - action_text:
        - string
    - action_date:
        - timestamp
        - required: true
        - unique: true
    - user_id:
        - int64
        - required: true

